config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit'
  patch 'books/:id' => 'books#update', as: 'update'
  delete 'books/:id' => 'books#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path
  end
  
  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_with model: @book,url: update_path(@book.id), method: :patch do |f| %>
<h1>Title</h1>
<%= f.text_field :title %>
<h1>Body</h1>
<%= f.text_area :body %>
<%= f.submit 'Update Book' %>
<% end %>
<%= link_to 'show', book_path %>
<%= link_to 'back', books_path %>

app/views/books/index.html.erb
<h1>BOOKS</h1>
<table>
  <tr><th>Title</th><th>Body</th><th colspan="3"></th></tr>
  <% @books.each do |book| %>
  <tr><td><%= book.title %></td><td><%= book.body %></td>
  <td><%= link_to "show", book_path(book.id) %></td>
  <td><%= link_to "edit", edit_path(book.id) %></td>
  <td><%= link_to "destroy", destroy_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
  </tr>
  <% end %>
</table>

<h2>new book</h2>
<%= form_with model: @book,url:'/books',method: :post do |f| %>
  <h1>Title</h1>
  <%= f.text_field :title %>
  <h2>Body</h2>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p>Title:<%= @book.title %></p>

<p>Body:<%= @book.body %></p>

<%= link_to "back", books_path %>

app/views/homes/top.html.erb
<h1>Bookersへようこそ</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換するこができます。
</p>
<%= link_to "Start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>